# Generated by Django 6.1.1 on 2026-09-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_is_phone_verified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailverification",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RenameField(
            model_name="emailverification",
            old_name="token_hash",
            new_name="code_hash",
        ),
    ]