# Generated by Django 6.1.1 on 2026-10-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='last_donation',
        ),
    ]
