# Generated by Django 6.1.1 on 2026-09-29 12:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('MYSELF', 'Myself'), ('SOMEONE_ELSE', 'Someone Else')], max_length=20)),
                ('patient_name', models.CharField(max_length=150)),
                ('requester_relationship', models.CharField(choices=[('SELF', 'Self'), ('PARENT', 'Parent'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('RELATIVE', 'Relative'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], max_length=30)),
                ('other_relationship', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(choices=[('SURGERY', 'Surgery'), ('ACCIDENT', 'Accident'), ('EMERGENCY', 'Emergency'), ('TREATMENT', 'Treatment'), ('CHILDBIRTH', 'Childbirth'), ('OTHER', 'Other')], max_length=30)),
                ('purpose_other', models.CharField(blank=True, max_length=255)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_required', models.PositiveIntegerField()),
                ('units_fulfilled', models.PositiveIntegerField(default=0)),
                ('urgency', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('URGENT', 'Urgent'), ('SCHEDULED', 'Scheduled')], max_length=20)),
                ('required_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('hospital_name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('contact_type', models.CharField(choices=[('MY_PHONE', 'My Phone'), ('OTHER_PHONE', 'Other Phone')], max_length=20)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_verified_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('units_required__gte', 1)), name='blood_request_units_required_gte_1'), models.CheckConstraint(condition=models.Q(('units_fulfilled__gte', 0)), name='blood_request_units_fulfilled_gte_0'), models.CheckConstraint(condition=models.Q(('units_fulfilled__lte', models.F('units_required'))), name='blood_request_units_fulfilled_lte_required')],
            },
        ),
    ]
