# Generated by Django 6.1.1 on 2026-10-02 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_is_available_profile_last_donation'),
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='request_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DIRECT', 'Direct')], default='GENERAL', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='target_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_blood_requests', to='accounts.profile'),
        ),
        migrations.AddConstraint(
            model_name='bloodrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request_type', 'GENERAL'), ('target_donor__isnull', True)), models.Q(('request_type', 'DIRECT'), ('target_donor__isnull', False)), _connector='OR'), name='blood_request_type_target_donor_consistent'),
        ),
        migrations.AddField(
            model_name='bloodrequestresponse',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='blood_requests.bloodrequest'),
        ),
        migrations.AddField(
            model_name='bloodrequestresponse',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_request_responses', to='accounts.profile'),
        ),
        migrations.AddConstraint(
            model_name='bloodrequestresponse',
            constraint=models.UniqueConstraint(fields=('blood_request', 'donor'), name='unique_blood_request_donor_response'),
        ),
    ]
