# Generated by Django 6.1.1 on 2026-10-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_is_available_profile_last_donation'),
        ('blood_requests', '0002_bloodrequestresponse_bloodrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequestresponse',
            name='units_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='target_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_blood_requests', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='bloodrequestresponse',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='bloodrequestresponse',
            constraint=models.CheckConstraint(condition=models.Q(('units_completed__gte', 0)), name='blood_request_response_units_completed_gte_0'),
        ),
    ]
