# Generated by Django 6.1.1 on 2026-09-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPulze',
        ),
    ]
